version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
    volumes:   
      - ./data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

